Updated the functions from the base library

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1429,3 +1429,65 @@ execute_unless()
 	( exec "${@}" )
 	return ${?}
 }
+
+#
+# usage: fips_enabled
+#
+# Check to see if FIPS is enabled, and return
+# a 0 status if it is, non-0 if it is not.
+#
+fips_enabled()
+{
+	[ -v FIPS_FLAG_FILE ] || FIPS_FLAG_FILE="/proc/sys/crypto/fips_enabled"
+
+	# If the flag file isn't there and readable, fail
+	is_file_readable "${FIPS_FLAG_FILE}" || return 2
+
+	# If we can't read the flag file's contents, fail
+	local FIPS_FLAG="$(<"${FIPS_FLAG_FILE}")" || return 3
+
+	# If the contents of the flag file aren't a number, fail
+	[[ "${FIPS_FLAG}" =~ ^[1-9][0-9]*$ ]] || return 4
+
+	# If the number from the flag file is not 1, fail
+	[ ${FIPS_FLAG} -eq 1 ] || return 1
+
+	# The flag file is there and contains a non-0 number
+	return 0
+}
+
+#
+# usage: get_namespace
+#
+# Get the current Kubernetes namespace
+#
+get_namespace()
+{
+	# If we don't know our namespace, we figure it out
+	for NS in KUBERNETES POD ; do
+		V="${NS}_NAMESPACE"
+		[ -v "${V}" ] || continue
+		[ -n "${!V}" ] && echo "${!V}" && return 0
+	done
+	return 0
+}
+
+#
+# usage: get_cluster_domain
+#
+# Compute the cluster domain for the current pod, if possible
+#
+get_cluster_domain()
+{
+	if [ -v CLUSTER_DOMAIN ] && [ -n "${CLUSTER_DOMAIN}" ] ; then
+		echo -n "${CLUSTER_DOMAIN}"
+		return 0
+	fi
+
+	# If we don't know our namespace, we figure it out
+	local NAMESPACE="$(get_namespace)"
+	[ -n "${NAMESPACE}" ] || return 0
+
+	# Let's see what we can do
+	hostname -f | sed -e "s;^.*\.${NAMESPACE}\.svc\.;;g"
+}
