Update to match the latest mvn-get

diff --git a/scripts/mvn-get b/scripts/mvn-get
--- a/scripts/mvn-get
+++ b/scripts/mvn-get
@@ -1,8 +1,4 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${0}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
-
 set -euo pipefail
 . /.functions
 
@@ -13,17 +9,13 @@ download()
 	local DEST="${3:-""}"
 	[ -n "${AUTH}" ] && AUTH="--user ${AUTH}"
 	[ -n "${DEST}" ] && DEST=(--output "${DEST}")
-	"${CURL}" --location --fail --disallow-username-in-url --config <(echo -n "${AUTH}") "${DEST[@]}" "${URL}"
+	curl --location --fail --disallow-username-in-url --config <(echo -n "${AUTH}") "${DEST[@]}" "${URL}"
 }
 
-decrypt() {
+decrypt()
+{
 	local VALUE="${1}"
-
-	local REQUIRED="${2:-"false"}"
-	case "${REQUIRED,,}" in
-		true ) REQUIRED="true" ;;
-		* ) REQUIRED="false" ;;
-	esac
+	local REQUIRED="$(to_boolean "${2:-"false"}")"
 
 	if "${REQUIRED}" ; then
 		[ -v MVN_GET_ENCRYPTION_KEY ] || fail "No MVN_GET_ENCRYPTION_KEY value is set, cannot continue"
@@ -48,35 +40,22 @@ decrypt() {
 usage()
 {
 	{
-		echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} artifactSpec [repoUrl] target"
+		echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} artifactSpec repoUrl target"
 		echo -e ""
 		echo -e "\t\tartifactSpec: groupId:artifactId[:version[:packaging[:classifier]]]"
 		echo -e "\t\trepoUrl:      URL to the Maven repository housing the artifact (http:// or https://)"
 		echo -e "\t\ttarget:       The final path where the file will be copied into. If it's"
 		echo -e "\t\t              a directory, the downloaded filename will be preserved."
 		echo -e ""
-		echo -e "\t\tIf the repoUrl is not given, the repository specified by the MVN_CENTRAL_REPO"
-		echo -e "\t\twill be used. If this variable is not set, empty, or invalid, then the default"
-		echo -e "\t\tMaven Central Repository URL at https://repo1.maven.org/maven2 will be used."
 	} 1>&2
 	exit 1
 }
 
-[ ${#} -ge 2 ] && [ ${#} -le 3 ] || usage
+[ ${#} -eq 3 ] || usage
 
-if [ ${#} -eq 3 ] ; then
-	ARTIFACT="${1}"
-	REPO_URL="${2}"
-	DEST="${3}"
-else
-	ARTIFACT="${1}"
-	DEST="${2}"
-
-	[ -v MVN_CENTRAL_REPO ] || MVN_CENTRAL_REPO=""
-	[[ "${MVN_CENTRAL_REPO,,}" =~ ^https?:// ]] || MVN_CENTRAL_REPO="https://repo1.maven.org/maven2"
-	# TODO: More URL validation?
-	REPO_URL="${MVN_CENTRAL_REPO}"
-fi
+ARTIFACT="${1}"
+REPO_URL="${2}"
+DEST="${3}"
 
 [[ "${ARTIFACT}" =~ ^([^:[:space:]]+):([^:[:space:]]+)(:([^:[:space:]]+)?(:([^:[:space:]]+)?(:([^:[:space:]]+)?)?)?)?$ ]] || fail "The artifact string [${ARTIFACT}] is not valid"
 GROUP_ID="${BASH_REMATCH[1]}"
@@ -87,18 +66,16 @@ CLASSIFIER="${BASH_REMATCH[8]}"
 
 [ -n "${VERSION}" ] || VERSION="RELEASE"
 
-XMLSTARLET="$(type -P xmlstarlet)" || fail "xmlstarlet is not installed - cannot proceed"
-XMLLINT="$(type -P xmllint)" || fail "xmllint is not installed - cannot proceed"
-CURL="$(type -P curl)" || fail "curl is not installed - cannot proceed"
+require_exe xmlstarlet xmllint curl
 
 NEED_DECRYPT="true"
 if [ -v MVN_GET_SERVER_ID ] ; then
 	# We have a server ID whose username/password combo we wish to consume
 	[ -n "${MVN_GET_SERVER_ID}" ] || fail "The value in MVN_GET_SERVER_ID may not be the empty string"
-	MVN_CRYPT="$(type -P "${BASEDIR}/mvn-crypt")" || MVN_CRYPT="$(type -P mvn-crypt)" || fail "mvn-crypt is not installed - cannot proceed"
-	MVN_GET_USERNAME="$("${MVN_CRYPT}" --quiet server decrypt "${MVN_GET_SERVER_ID}" username)"
+	require_exe mvn-crypt
+	MVN_GET_USERNAME="$(mvn-crypt --quiet server decrypt "${MVN_GET_SERVER_ID}" username)"
 	[ -n "${MVN_GET_USERNAME}" ] || fail "The username for server [${MVN_GET_SERVER_ID}] is empty or nonexistent"
-	MVN_GET_PASSWORD="$("${MVN_CRYPT}" --quiet server decrypt "${MVN_GET_SERVER_ID}" password)"
+	MVN_GET_PASSWORD="$(mvn-crypt --quiet server decrypt "${MVN_GET_SERVER_ID}" password)"
 	[ -n "${MVN_GET_PASSWORD}" ] || fail "The password for server [${MVN_GET_SERVER_ID}] is empty or nonexistent"
 	NEED_DECRYPT="false"
 fi
@@ -124,7 +101,7 @@ fi
 GROUP_PATH="${GROUP_ID//./\/}"
 BASE="${REPO_URL}/${GROUP_PATH}/${ARTIFACT_ID}"
 
-say "👉 Downloading:"
+doing "Downloading:"
 say "\tArtifact:    [${ARTIFACT}]"
 say "\tRepository:  [${REPO_URL}]"
 say "\tDestination: [${DEST}]"
@@ -137,8 +114,8 @@ if [ "${VERSION}" == "LATEST" ] || [ "${VERSION}" == "RELEASE" ] ; then
 	[ "${VERSION}" == "RELEASE" ] && SUPPORT_SNAPSHOT="false"
 	say "⚠️ Identifying the ${VERSION} artifact version to download..."
 	XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID} from [${BASE}/maven-metadata.xml]"
-	"${XMLLINT}" - <<< "${XML}" &>/dev/null || fail "The artifact metadata for ${GROUP_ID}:${ARTIFACT_ID} downloaded from [${BASE}/maven-metadata.xml] is not valid XML"
-	FINAL_VERSION="$("${XMLSTARLET}" sel -t -v "/metadata/versioning/${VERSION,,}" <<< "${XML}")" || fail "Failed to identify the ${VERSION} version for ${GROUP_ID}:${ARTIFACT_ID} from the XML at [${BASE}/maven-metadata.xml]"
+	xmllint - <<< "${XML}" &>/dev/null || fail "The artifact metadata for ${GROUP_ID}:${ARTIFACT_ID} downloaded from [${BASE}/maven-metadata.xml] is not valid XML"
+	FINAL_VERSION="$(xmlstarlet sel -t -v "/metadata/versioning/${VERSION,,}" <<< "${XML}")" || fail "Failed to identify the ${VERSION} version for ${GROUP_ID}:${ARTIFACT_ID} from the XML at [${BASE}/maven-metadata.xml]"
 	say "\t✅ The ${VERSION} version is ${FINAL_VERSION}"
 	VERSION="${FINAL_VERSION}"
 fi
@@ -148,9 +125,9 @@ BASE+="/${VERSION}"
 if "${SUPPORT_SNAPSHOT}" && [[ "${VERSION^^}" =~ (^|[^a-zA-Z0-9])SNAPSHOT$ ]] ; then
 	say "⚠️ This version is a SNAPSHOT - identifying the final artifact to download"
 	XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}/maven-metadata.xml]"
-	"${XMLLINT}" - <<< "${XML}" &>/dev/null || fail "The artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} downloaded from [${BASE}/maven-metadata.xml] is not valid XML"
-	TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${XML}")" || fail "No timestamp data is present for the required snapshot version, cannot continue"
-	BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${XML}")" || fail "No build number data is present for the required snapshot version, cannot continue"
+	xmllint - <<< "${XML}" &>/dev/null || fail "The artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} downloaded from [${BASE}/maven-metadata.xml] is not valid XML"
+	TIMESTAMP="$(xmlstarlet sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${XML}")" || fail "No timestamp data is present for the required snapshot version, cannot continue"
+	BUILD_NUMBER="$(xmlstarlet sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${XML}")" || fail "No build number data is present for the required snapshot version, cannot continue"
 	FINAL_VERSION="$(echo -n "${VERSION}" | /usr/bin/sed -e "s/\(\b\)SNAPSHOT\(\b\)/\1${TIMESTAMP}-${BUILD_NUMBER}\2/gi")"
 	say "\t✅ The latest SNAPSHOT version is ${FINAL_VERSION}"
 fi
@@ -160,8 +137,8 @@ TAB=""
 if [ -z "${EXTENSION}" ] ; then
 	say "⚠️ Packaging (type) not provided, must identify it from the POM"
 	POM="$(download "${BASE}.pom" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}.pom]"
-	"${XMLLINT}" - <<< "${POM}" &>/dev/null || fail "The artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} downloaded from [${BASE}.pom] is not valid XML"
-	EXTENSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")" || true
+	xmllint - <<< "${POM}" &>/dev/null || fail "The artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} downloaded from [${BASE}.pom] is not valid XML"
+	EXTENSION="$(xmlstarlet sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")" || true
 	[ -z "${EXTENSION}" ] && EXTENSION="jar"
 	TAB="\t"
 fi
@@ -197,14 +174,10 @@ else
 	DEST="${PARENT}/$(basename "${DEST}")"
 fi
 
-say "👉 Final Version: [${FINAL_VERSION}]"
-say "👉 Final File:    [${DEST}]"
-say "👉 Final URL:     [${URL}]"
+doing "Final Version: [${FINAL_VERSION}]"
+doing "Final File:    [${DEST}]"
+doing "Final URL:     [${URL}]"
 download "${URL}" "${AUTH}" "${DEST}" || fail "Failed to complete the download"
-say "\t✅ Download successful!"
-
-RENDER_HELPERS="$(type -P "${BASEDIR}/render-helpers")" || \
-	RENDER_HELPERS="$(type -P render-helpers)" && \
-	"${RENDER_HELPERS}" "${DEST}" "${FINAL_VERSION}"
-
-exit 0
+ok "Download successful!"
+type -P render-helpers &>/dev/null || exit 0
+execute render-helpers "${DEST}" "${FINAL_VERSION}"
